baseurl = "/"
languageCode = "en-US"
title = "Anna Kurtin"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/post/:year/:month/:day/:slug"

[params]
  avatar = "annaprofile.png"
  author = "Anna Kurtin"
  occupation = "master's student in wildlife biology at the University of Montana"
  about = "My current interests include wildlife biology, animal behavior, bioacoustics, and conservation. I am also an active runner and love to play music on my free time!"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "annakurtin"
  Email         = "annak26625@gmail.com"
  Twitter       = "AnnaKurtin"
  LinkedIn      = "anna-kurtin"
#  Instagram     = "username"
#  Stackoverflow = "username"
#  Medium        = "username"
#  Telegram      = "username"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/post/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"
